import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header"; // <-- adjust the path if needed

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Saikat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header /> {/* Added Header here */}
        <main>{children}</main>
      </body>
    </html>
  );
}

/*
import type { Metadata } from "next";
import Header from "../components/Header";
import Footer from "../components/Footer";

export const metadata: Metadata = {
  title: "School Management",
  description: "Admin & Teacher Panel",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{ margin: 0, fontFamily: "Arial, sans-serif" }}>
        <Header />
        <main style={{ padding: "20px", minHeight: "80vh" }}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}*//*
import type { Metadata } from "next";
import Header from "../components/Header";
import Footer from "../components/Footer";

export const metadata: Metadata = {
  title: "School Management",
  description: "Admin & Teacher Panel",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{ margin: 0, fontFamily: "Arial, sans-serif" }}>
        <Header />
        <main style={{ padding: "20px", minHeight: "80vh" }}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}/*//////////////////////////////////////
/*
import type { Metadata } from "next";
import Header from "../components/Header";
import Footer from "../components/Footer";
import "../styles/globals.css"; // 👈 TailwindCSS global styles import
 
export const metadata: Metadata = {
  title: "School Management",
  description: "Admin & Teacher Panel",
};
 
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
<html lang="en">
<body className="m-0 font-sans bg-gray-100 text-gray-900">
        
<Header />
 
       
<main className="p-6 min-h-[80vh]">{children}</main>
 
      
<Footer />
</body>
</html>
  );
}


*/
/*import type { Metadata } from "next";
import Header from "../components/Header";
import Footer from "../components/Footer";
import "../styles/globals.css"; 

export const metadata: Metadata = {
  title: "School Management",
  description: "Admin & Teacher Panel",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="m-0 font-sans bg-gray-100 text-gray-900">
        <Header />

        <main className="p-6 min-h-[90vh]">
         
          <div className="flex justify-center">
            <div className="w-[40%]">
              {children}
            </div>
          </div>
        </main>

        <Footer />
      </body>
    </html>
  );
}*/
